language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install

after_success:
  - ./after_success.sh

notifications:
  email:
  - herve.tchepannou@gmail.com

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "repository.tchepannou"
  upload-dir: kiosk-core
  on:
    branch: master
